name: Deploy Node.js Kafka App

on:
  push:
    branches:
      - main     # Run on every push to main branch
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build your app (if applicable)
      - name: Build application
        run: npm run build

      # Step 5: Deploy build to your Oracle Linux server
      - name: Deploy to Oracle Linux Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: root
          SERVER_HOST: 10.1.14.101
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Create target folder on remote server
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "mkdir -p /var/www/myapp"

          # Copy build files to server
          rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" ./ $SERVER_USER@$SERVER_HOST:/var/www/myapp/

          # Optional: Restart the Node.js process (pm2 or systemctl)
          ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
            cd /var/www/myapp &&
            npm install --production &&
            pm2 restart all || pm2 start server.js --name myapp
          "
